openapi: 3.0.0
info:
  title: Unknown
  version: 1.0.0
servers: 
  - url: http://192.168.3.12:8080/v1
paths:
  /trivias:
    get: 
      tags: 
        - trivias
      summary: "トリビア情報API"
      description: "検索された情報を返します"
      parameters:
        - name: "keyword"
          in: query
          description: "検索したいキーワード"
          required: false
          schema: 
            type: string
        - name: "genreId"
          in: query
          description: "検索したいジャンル"
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: A JSON array of Trivia model
          content:
            apllication/json:
              schema: 
                type: array
    post:
      tags: 
        - trivias
      summary: トリビア登録API
      description: トリビアを登録します
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId: 
                  type: integer
                genreId:
                  type: integer
                content:
                  type: string
      responses:
        "200":
          description: ok
      security:
        - bearer: []
  /users:
    post:
      tags:
        - /users
      description: ユーザを登録します
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userName:
                  type: string
                emailAdress:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: ok
components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer